In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

<h3 style="color:orange;text-align:center">Groupby Methods [Huge Categories] </h3>

1. agg()
2. aggregate()
3. sum()
4. mean()
5. median()
6. min()
7. max()
8. count()
9. size()
10. std()
11. var()
12. sem()
13. prod()
14. first()
15. last()
16. nth()
17. transform()
18. filter()
19. ngroup()
20. cumcount()

In [2]:
df = pd.DataFrame({
  "Department":np.random.choice(['IT','HR','Sales'],9),
  "Employee":['A','B','C','D','E','F','G','H','I'],
  'Salary':[60000,70000,50000,52000,45000,47000,65000,51000,48000],
  'Experience':[5,7,3,4,2,3,6,4,3]
})

print(df)

  Department Employee  Salary  Experience
0         HR        A   60000           5
1      Sales        B   70000           7
2         HR        C   50000           3
3         HR        D   52000           4
4         HR        E   45000           2
5         IT        F   47000           3
6         IT        G   65000           6
7         HR        H   51000           4
8         HR        I   48000           3

In [3]:
# groupby() -> split-apply-combine

df.groupby('Department')

In [4]:
# sum

# -> total salary per department

df.groupby('Department')['Salary'].sum()

Department
HR       306000
IT       112000
Sales     70000
Name: Salary, dtype: int64

In [5]:
# mean

# -> average salary per department

df.groupby('Department')['Salary'].mean().round()

Department
HR       51000.0
IT       56000.0
Sales    70000.0
Name: Salary, dtype: float64

In [6]:
# medain

# -> middel values

df.groupby('Department')['Salary'].median()

Department
HR       50500.0
IT       56000.0
Sales    70000.0
Name: Salary, dtype: float64

In [7]:
# min,max

# -> minimum and maximum values in each department

print(df.groupby('Department')['Salary'].min())
print(df.groupby('Department')['Salary'].max())

Department
HR       45000
IT       47000
Sales    70000
Name: Salary, dtype: int64
Department
HR       60000
IT       65000
Sales    70000
Name: Salary, dtype: int64

In [8]:
# count()

# -> counts non-null values only

df.groupby('Department')['Salary'].count()

Department
HR       6
IT       2
Sales    1
Name: Salary, dtype: int64

In [9]:
# size()

# -> count all rows including null values

df.groupby('Department')['Salary'].size()

Department
HR       6
IT       2
Sales    1
Name: Salary, dtype: int64

In [10]:
# std -> standard deviation

df.groupby('Department')['Salary'].std()

Department
HR        5059.644256
IT       12727.922061
Sales             NaN
Name: Salary, dtype: float64

In [11]:
# var -> variance

df.groupby('Department')['Salary'].var()

Department
HR        25600000.0
IT       162000000.0
Sales            NaN
Name: Salary, dtype: float64

In [12]:
# sem -> Standard Error

df.groupby('Department')['Salary'].sem()

Department
HR       2065.591118
IT       9000.000000
Sales            NaN
Name: Salary, dtype: float64

In [13]:
# prod() -> Product

df.groupby('Department')['Experience'].prod()

Department
HR       1440
IT         18
Sales       7
Name: Experience, dtype: int64

In [14]:
# first(),last() rows in each group

print(df.groupby('Department').first())

print(df.groupby('Department').last())

# nth row
print(df.groupby('Department').nth(2))

           Employee  Salary  Experience
Department
HR                A   60000           5
IT                F   47000           3
Sales             B   70000           7
           Employee  Salary  Experience
Department
HR                I   48000           3
IT                G   65000           6
Sales             B   70000           7
  Department Employee  Salary  Experience
3         HR        D   52000           4

```
agg() / aggregate()
```

In [15]:
df.groupby('Department')['Salary'].agg(['sum','mean','max']).round()

               sum     mean    max
Department
HR          306000  51000.0  60000
IT          112000  56000.0  65000
Sales        70000  70000.0  70000

In [16]:
print(df.groupby('Department').agg({
  'Salary':['sum','mean'],
  'Experience':['max','min']
}).round())

            Salary          Experience
               sum     mean        max min
Department
HR          306000  51000.0          5   2
IT          112000  56000.0          6   3
Sales        70000  70000.0          7   7

```
transform()
```
1. Returns same size output as original DataFrame

In [17]:
df['Avg_salary'] = df.groupby('Department')['Salary'].transform('mean').round()

print(df)

  Department Employee  Salary  Experience  Avg_salary
0         HR        A   60000           5     51000.0
1      Sales        B   70000           7     70000.0
2         HR        C   50000           3     51000.0
3         HR        D   52000           4     51000.0
4         HR        E   45000           2     51000.0
5         IT        F   47000           3     56000.0
6         IT        G   65000           6     56000.0
7         HR        H   51000           4     51000.0
8         HR        I   48000           3     51000.0

```
filter()
```
1. Filters groups based on condition

In [18]:
df.groupby('Department').filter(lambda x:x['Salary'].mean() > 50000)

  Department Employee  Salary  Experience  Avg_salary
0         HR        A   60000           5     51000.0
1      Sales        B   70000           7     70000.0
2         HR        C   50000           3     51000.0
3         HR        D   52000           4     51000.0
4         HR        E   45000           2     51000.0
5         IT        F   47000           3     56000.0
6         IT        G   65000           6     56000.0
7         HR        H   51000           4     51000.0
8         HR        I   48000           3     51000.0

```
ngroup()
```
1. Assigns group numbers

In [19]:
df['Group_ID'] = df.groupby('Department').ngroup()

print(df)

  Department Employee  Salary  Experience  Avg_salary  Group_ID
0         HR        A   60000           5     51000.0         0
1      Sales        B   70000           7     70000.0         2
2         HR        C   50000           3     51000.0         0
3         HR        D   52000           4     51000.0         0
4         HR        E   45000           2     51000.0         0
5         IT        F   47000           3     56000.0         1
6         IT        G   65000           6     56000.0         1
7         HR        H   51000           4     51000.0         0
8         HR        I   48000           3     51000.0         0

```
cumcount()
```
1. Counts occurences within group

In [20]:
df['Count'] = df.groupby('Department').cumcount()

print(df)

  Department Employee  Salary  Experience  Avg_salary  Group_ID  Count
0         HR        A   60000           5     51000.0         0      0
1      Sales        B   70000           7     70000.0         2      0
2         HR        C   50000           3     51000.0         0      1
3         HR        D   52000           4     51000.0         0      2
4         HR        E   45000           2     51000.0         0      3
5         IT        F   47000           3     56000.0         1      0
6         IT        G   65000           6     56000.0         1      1
7         HR        H   51000           4     51000.0         0      4
8         HR        I   48000           3     51000.0         0      5

<h3 style='color:orange;text-align:center'>Statistics Methods </h3>

1. mean
2. median
3. mode
4. var
5. std
6. mad
7. quantile
8. skew
9. kurt
10. corr
11. cov

In [21]:
df = pd.DataFrame({
    'Product': ['A','B','C','D','E','F','G','H'],
    'Sales': [100, 150, 200, 250, 300, 1000, 120, 180],
    'Profit': [10, 20, 30, 25, 40, 200, 15, 22],
    'Discount': [5, 10, 0, 15, 20, 50, 5, 10],
    "category":np.random.choice(['Bedroom','Kitchen','Garden'],8)
})

print(df)

  Product  Sales  Profit  Discount category
0       A    100      10         5  Bedroom
1       B    150      20        10   Garden
2       C    200      30         0  Bedroom
3       D    250      25        15   Garden
4       E    300      40        20   Garden
5       F   1000     200        50   Garden
6       G    120      15         5  Kitchen
7       H    180      22        10   Garden

In [22]:
# mean

df['Sales'].mean()

np.float64(287.5)

In [23]:
# mode -> most Frequent value

df['category'].mode()

0    Garden
Name: category, dtype: object

In [24]:
# quantile -> percentiles

df['Sales'].quantile([0.25,0.5,0.75])

0.25    142.5
0.50    190.0
0.75    262.5
Name: Sales, dtype: float64

In [25]:
# skew -> asymmetry of data

df['Sales'].skew()

np.float64(2.5573799321116817)

In [26]:
# kurtosis -> peakedness / tail heaviness

df['Sales'].kurt()

np.float64(6.830691694675181)

In [27]:
# corr() -> correlation

df[['Sales','Profit','Discount']].corr()

             Sales    Profit  Discount
Sales     1.000000  0.994598  0.958792
Profit    0.994598  1.000000  0.939245
Discount  0.958792  0.939245  1.000000

In [28]:
df[['Sales','Profit','Discount']].cov()

                 Sales        Profit     Discount
Sales     87221.428571  18562.142857  4441.071429
Profit    18562.142857   3993.357143   930.892857
Discount   4441.071429    930.892857   245.982143

<h3 style='color:red;text-align:center'>Window Methods</h3>


1. rolling
2. expanding

```
rolling
```
1. window -> size of window
2. min_periods -> minimum values required
3. center of window

In [29]:
df['Sales'].rolling(window=3,min_periods=1).mean().round()

0    100.0
1    125.0
2    150.0
3    200.0
4    250.0
5    517.0
6    473.0
7    433.0
Name: Sales, dtype: float64

In [30]:
df['Sales'].rolling(window=3,min_periods=1).sum().round()

# like wise std also

0     100.0
1     250.0
2     450.0
3     600.0
4     750.0
5    1550.0
6    1420.0
7    1300.0
Name: Sales, dtype: float64

```
expanding
```

In [31]:
df['Sales'].expanding().mean() # like wise sum and std

0    100.000000
1    125.000000
2    150.000000
3    175.000000
4    200.000000
5    333.333333
6    302.857143
7    287.500000
Name: Sales, dtype: float64

<h3 style="color:orange;text-align:center">Reshaping Methods</h3>

1. pivot
2. pivot_table
3. melt
4. stack
5. unstack

```
pivot
```

1. Does not Handles Duplicate

In [32]:
# # Methods
# 1. index
# 2. columns
# 3. values
# 4. aggfun

In [33]:
df = pd.DataFrame({
  'Date':['2024-01','2024-01','2024-02','2024-02'],
  'Product':['A','B','A','B'],
  'Sales':[100,200,150,250]
})

print(df)

      Date Product  Sales
0  2024-01       A    100
1  2024-01       B    200
2  2024-02       A    150
3  2024-02       B    250

In [34]:
# conveerting two pivot

print(df.pivot(index='Date',columns='Product',values='Sales'))

Product    A    B
Date
2024-01  100  200
2024-02  150  250

```
pivot_table
```

1. Handles Duplicate values

In [35]:
print(df.pivot_table(index='Date',columns='Product',values='Sales',aggfunc='sum'))

Product    A    B
Date
2024-01  100  200
2024-02  150  250

```
melt
```

1. Opposite of pivot

In [36]:
# id_vars -> columns keep it as unchanged
# value_vars -> columns you want to convert into rows
# var_name -> Name of the column
# value_name -> Name for the vlaues column

In [37]:
df = pd.DataFrame({
  'Name':['Ram','Shyam'],
  'Math':[90,80],
  'Science':[85,75]
})

result = pd.melt(
  df,
  id_vars=['Name'],
  value_vars=['Math','Science'],
  var_name='Subject',
  value_name='Marks'
)

print(result)

    Name  Subject  Marks
0    Ram     Math     90
1  Shyam     Math     80
2    Ram  Science     85
3  Shyam  Science     75

```
stack
```

1. Converts columns -> rows (multi-index)

In [38]:
df = pd.DataFrame({
  'A':[1,2],
  'B':[3,4]
})

print(df.stack())

0  A    1
   B    3
1  A    2
   B    4
dtype: int64

```
unstack()
```

1. convert row index -> columns

In [39]:
df = df.stack()

print(df.unstack())

   A  B
0  1  3
1  2  4

<h3 style='color:pink;text-align:center'>Time Series Methods </h3>

1. to_datetime()
2. to_timedelta()
3. date_range()
4. resample()
5. asfreq()
6. shift()
7. tshift()
8. diff()
9. tz_localize()
10. tz_convert()

In [40]:
df = pd.DataFrame({
  'Date':pd.date_range('2024-01-01',periods=5,freq='D'),
  'Sales':[100,150,200,130,170]
})

print(df)

        Date  Sales
0 2024-01-01    100
1 2024-01-02    150
2 2024-01-03    200
3 2024-01-04    130
4 2024-01-05    170

```
to_datetime() -> convert string to datetime
```

In [41]:
df['Date'] = pd.to_datetime(df['Date'])
print(df)

        Date  Sales
0 2024-01-01    100
1 2024-01-02    150
2 2024-01-03    200
3 2024-01-04    130
4 2024-01-05    170

```
to_timedelta() -> converts time diffrences
```

In [42]:
# Units
# 1. D = Days
# 2. H = Hours
# 3. m = Minutes
# 4. s = Seconds
# 5. ms = milliseconds
# 6. us = Microseconds
# 7. ns = Nanoseconds

In [43]:
df['days_added'] = pd.to_timedelta(df['Sales'],unit='D')

df['Shipping_date'] = df['Date'] + df['days_added']
print(df)

        Date  Sales days_added Shipping_date
0 2024-01-01    100   100 days    2024-04-10
1 2024-01-02    150   150 days    2024-05-31
2 2024-01-03    200   200 days    2024-07-21
3 2024-01-04    130   130 days    2024-05-13
4 2024-01-05    170   170 days    2024-06-23

```
resample
```

1. Change time frequency

In [44]:
dff = df.copy()

dff = dff.set_index('Date')

print(dff)

            Sales days_added Shipping_date
Date
2024-01-01    100   100 days    2024-04-10
2024-01-02    150   150 days    2024-05-31
2024-01-03    200   200 days    2024-07-21
2024-01-04    130   130 days    2024-05-13
2024-01-05    170   170 days    2024-06-23

In [45]:
# Daily -> Monthly sales

print(dff.resample('ME').agg({
  'Sales':'sum'
}))

            Sales
Date
2024-01-31    750

In [46]:
# shift
# -> shift data up/down

dff['prev_sales'] = dff['Sales'].shift(1)

print(dff)

            Sales days_added Shipping_date  prev_sales
Date
2024-01-01    100   100 days    2024-04-10         NaN
2024-01-02    150   150 days    2024-05-31       100.0
2024-01-03    200   200 days    2024-07-21       150.0
2024-01-04    130   130 days    2024-05-13       200.0
2024-01-05    170   170 days    2024-06-23       130.0

In [47]:
# diff() => Diffrence between rows

dff['daily_change'] = dff['Sales'].diff()

print(dff)

            Sales days_added Shipping_date  prev_sales  daily_change
Date
2024-01-01    100   100 days    2024-04-10         NaN           NaN
2024-01-02    150   150 days    2024-05-31       100.0          50.0
2024-01-03    200   200 days    2024-07-21       150.0          50.0
2024-01-04    130   130 days    2024-05-13       200.0         -70.0
2024-01-05    170   170 days    2024-06-23       130.0          40.0

In [48]:
# convert timezone

dff = dff.tz_localize('Asia/Kolkata')

print(dff)

                           Sales days_added Shipping_date  prev_sales  \
Date
2024-01-01 00:00:00+05:30    100   100 days    2024-04-10         NaN
2024-01-02 00:00:00+05:30    150   150 days    2024-05-31       100.0
2024-01-03 00:00:00+05:30    200   200 days    2024-07-21       150.0
2024-01-04 00:00:00+05:30    130   130 days    2024-05-13       200.0
2024-01-05 00:00:00+05:30    170   170 days    2024-06-23       130.0

                           daily_change
Date
2024-01-01 00:00:00+05:30           NaN
2024-01-02 00:00:00+05:30          50.0
2024-01-03 00:00:00+05:30          50.0
2024-01-04 00:00:00+05:30         -70.0
2024-01-05 00:00:00+05:30          40.0

<h3 style="color:blue;text-align:center">String Methods</h3>

In [49]:
df = pd.DataFrame({
  "Name":['Ram','Shyam','ANIL Kumar'],
  "Email":['ram@gmail.com','shyam@yahoo.com','anil@outlook.com'],
  'City':['Hyderabad','Delhi','Mumbai']
})

print(df)

         Name             Email       City
0         Ram     ram@gmail.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  ANIL Kumar  anil@outlook.com     Mumbai

In [50]:
# convert to lower case

df['Name'] = df['Name'].str.lower()

print(df)

         Name             Email       City
0         ram     ram@gmail.com  Hyderabad
1       shyam   shyam@yahoo.com      Delhi
2  anil kumar  anil@outlook.com     Mumbai

In [51]:
# convert to upper case
df['Name'] = df['Name'].str.upper()

print(df)

         Name             Email       City
0         RAM     ram@gmail.com  Hyderabad
1       SHYAM   shyam@yahoo.com      Delhi
2  ANIL KUMAR  anil@outlook.com     Mumbai

In [52]:
# title => Capitalize each word

df['Name'] = df['Name'].str.title()

print(df)

         Name             Email       City
0         Ram     ram@gmail.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  Anil Kumar  anil@outlook.com     Mumbai

In [53]:
# strip -> Remove spaces

df['Email'] = df['Email'].str.strip()

print(df)

         Name             Email       City
0         Ram     ram@gmail.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  Anil Kumar  anil@outlook.com     Mumbai

In [54]:
# remove left spaces

df['Name'] = df['Name'].str.lstrip()

print(df)

         Name             Email       City
0         Ram     ram@gmail.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  Anil Kumar  anil@outlook.com     Mumbai

In [55]:
# remove right spaces

df['Name'] = df['Name'].str.rstrip()

print(df)

         Name             Email       City
0         Ram     ram@gmail.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  Anil Kumar  anil@outlook.com     Mumbai

In [56]:
# replace text

df['Email'] = df['Email'].str.replace('gmail','google')
print(df)

         Name             Email       City
0         Ram    ram@google.com  Hyderabad
1       Shyam   shyam@yahoo.com      Delhi
2  Anil Kumar  anil@outlook.com     Mumbai

In [57]:
# check substring

df['Email'].str.contains('google')

0     True
1    False
2    False
Name: Email, dtype: bool

In [58]:
# check starting

df['Name'].str.startswith('R')

0     True
1    False
2    False
Name: Name, dtype: bool

In [59]:
# checking ending

df['Email'].str.endswith('.com')

0    True
1    True
2    True
Name: Email, dtype: bool

In [60]:
# split the string into list

df['Email'].str.split('@')

0      [ram, google.com]
1     [shyam, yahoo.com]
2    [anil, outlook.com]
Name: Email, dtype: object

In [61]:
# join list into string

df['City'].str.join('-')

0    H-y-d-e-r-a-b-a-d
1            D-e-l-h-i
2          M-u-m-b-a-i
Name: City, dtype: object

In [62]:
# length of string

df['Name'].str.len()

0     3
1     5
2    10
Name: Name, dtype: int64

In [63]:
# find position of substring

df['Email'].str.find('@')

0    3
1    5
2    4
Name: Email, dtype: int64

In [64]:
# get element by index

df['Email'].str.split('@').str.get(0)

0      ram
1    shyam
2     anil
Name: Email, dtype: object

<h3 style="color:orange;text-align:center">Mathematical Methods</h3>

In [65]:
df = pd.DataFrame({
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Laptop', 'Mobile'],
    'Price': [50000, 20000, 15000, 52000, 21000],
    'Quantity': [1, 2, 3, 1, 2],
    'Discount': [5000, 2000, 1500, 6000, 2500],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
})

print(df)

  Product  Price  Quantity  Discount     Category
0  Laptop  50000         1      5000  Electronics
1  Mobile  20000         2      2000  Electronics
2  Tablet  15000         3      1500  Electronics
3  Laptop  52000         1      6000  Electronics
4  Mobile  21000         2      2500  Electronics

In [66]:
# add

df['Total'] = df['Price'].add(df['Quantity'],fill_value=0)

print(df)

  Product  Price  Quantity  Discount     Category  Total
0  Laptop  50000         1      5000  Electronics  50001
1  Mobile  20000         2      2000  Electronics  20002
2  Tablet  15000         3      1500  Electronics  15003
3  Laptop  52000         1      6000  Electronics  52001
4  Mobile  21000         2      2500  Electronics  21002

In [67]:
# subtraction

df['Net'] = df['Price'].sub(df['Discount'])

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net
0  Laptop  50000         1      5000  Electronics  50001  45000
1  Mobile  20000         2      2000  Electronics  20002  18000
2  Tablet  15000         3      1500  Electronics  15003  13500
3  Laptop  52000         1      6000  Electronics  52001  46000
4  Mobile  21000         2      2500  Electronics  21002  18500

In [68]:
# Multiplication

df['Revenue'] = df['Price'].mul(df['Quantity'])

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

In [69]:
# division

df['price_per_item'] = df['Price'].div(df['Quantity'])

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item
0         50000.0
1         10000.0
2          5000.0
3         52000.0
4         10500.0

In [70]:
# power

df['Square'] = df['Quantity'].pow(2)

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square
0         50000.0       1
1         10000.0       4
2          5000.0       9
3         52000.0       1
4         10500.0       4

In [71]:
# absolute value

df['diff'] = (df['Price']-df['Discount']).abs()

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff
0         50000.0       1  45000
1         10000.0       4  18000
2          5000.0       9  13500
3         52000.0       1  46000
4         10500.0       4  18500

In [72]:
# Limit values

df['Price_limit'] = df['Price'].clip(lower=2000,upper=5000)

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff  Price_limit
0         50000.0       1  45000         5000
1         10000.0       4  18000         5000
2          5000.0       9  13500         5000
3         52000.0       1  46000         5000
4         10500.0       4  18500         5000

In [73]:
# eval -> perform expression

df.eval('Total_price = Price*Quantity - Discount',inplace=True)

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff  Price_limit  Total_price
0         50000.0       1  45000         5000        45000
1         10000.0       4  18000         5000        38000
2          5000.0       9  13500         5000        43500
3         52000.0       1  46000         5000        46000
4         10500.0       4  18500         5000        39500

In [74]:
# where
# -> Keep values if condition true, else replace

# IF condition TRUE → keep value  
# ELSE → replace

df['Price_where'] = df['Price'].where(df['Price']>20000,20000)
print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff  Price_limit  Total_price  Price_where
0         50000.0       1  45000         5000        45000        50000
1         10000.0       4  18000         5000        38000        20000
2          5000.0       9  13500         5000        43500        20000
3         52000.0       1  46000         5000        46000        52000
4         10500.0       4  18500         5000        39500        21000

In [75]:
# mask()
# Opposite of where

# IF condition TRUE → keep value  
# ELSE → replace

df['Price_mask'] = df['Price'].mask(df['Price']>20000,50000)

print(df)

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff  Price_limit  Total_price  Price_where  \
0         50000.0       1  45000         5000        45000        50000
1         10000.0       4  18000         5000        38000        20000
2          5000.0       9  13500         5000        43500        20000
3         52000.0       1  46000         5000        46000        52000
4         10500.0       4  18500         5000        39500        21000

   Price_mask
0       50000
1       20000
2       15000
3       50000
4       50000

In [79]:
# explode()
# Expand list into rows

df2 = pd.DataFrame({
  'Product':['Laptop','Mobile'],
  'Tags':[['Tech','Portable'],['Smart','Android']]
})


print(df2.explode('Tags'))

  Product      Tags
0  Laptop      Tech
0  Laptop  Portable
1  Mobile     Smart
1  Mobile   Android

In [80]:
# find duplicates

df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [82]:
# Remove duplicates

print(df.drop_duplicates())

  Product  Price  Quantity  Discount     Category  Total    Net  Revenue  \
0  Laptop  50000         1      5000  Electronics  50001  45000    50000
1  Mobile  20000         2      2000  Electronics  20002  18000    40000
2  Tablet  15000         3      1500  Electronics  15003  13500    45000
3  Laptop  52000         1      6000  Electronics  52001  46000    52000
4  Mobile  21000         2      2500  Electronics  21002  18500    42000

   price_per_item  Square   diff  Price_limit  Total_price  Price_where  \
0         50000.0       1  45000         5000        45000        50000
1         10000.0       4  18000         5000        38000        20000
2          5000.0       9  13500         5000        43500        20000
3         52000.0       1  46000         5000        46000        52000
4         10500.0       4  18500         5000        39500        21000

   Price_mask
0       50000
1       20000
2       15000
3       50000
4       50000

In [83]:
# drop()
# Remove rows/columns

df.drop('Category',axis=1,inplace=True)

print(df)

  Product  Price  Quantity  Discount  Total    Net  Revenue  price_per_item  \
0  Laptop  50000         1      5000  50001  45000    50000         50000.0
1  Mobile  20000         2      2000  20002  18000    40000         10000.0
2  Tablet  15000         3      1500  15003  13500    45000          5000.0
3  Laptop  52000         1      6000  52001  46000    52000         52000.0
4  Mobile  21000         2      2500  21002  18500    42000         10500.0

   Square   diff  Price_limit  Total_price  Price_where  Price_mask
0       1  45000         5000        45000        50000       50000
1       4  18000         5000        38000        20000       20000
2       9  13500         5000        43500        20000       15000
3       1  46000         5000        46000        52000       50000
4       4  18500         5000        39500        21000       50000

<h3 style='color:orange;text-align:center'>Index Methods</h3>

In [84]:
df = pd.DataFrame({
  'order_id':[101,102,103,104],
  'customer':['Ram','Shyam','Anil','Ram'],
  'City':['Hyderabad','Delhi','Mumbai','Hyderabad'],
  'Sales':[1000,1500,2000,1200]
})

print(df)

   order_id customer       City  Sales
0       101      Ram  Hyderabad   1000
1       102    Shyam      Delhi   1500
2       103     Anil     Mumbai   2000
3       104      Ram  Hyderabad   1200

In [86]:
# set_index => convert a column -> index

df = df.set_index('order_id')
print(df)

         customer       City  Sales
order_id
101           Ram  Hyderabad   1000
102         Shyam      Delhi   1500
103          Anil     Mumbai   2000
104           Ram  Hyderabad   1200

In [87]:
# reset_index() -> back to normal index

df = df.reset_index()

print(df)

   order_id customer       City  Sales
0       101      Ram  Hyderabad   1000
1       102    Shyam      Delhi   1500
2       103     Anil     Mumbai   2000
3       104      Ram  Hyderabad   1200

In [90]:
# rename => Rename columns or index labels

df.rename(columns={'Sales':'total_sales'},inplace=True)

print(df)

   order_id customer       City  total_sales
0       101      Ram  Hyderabad         1000
1       102    Shyam      Delhi         1500
2       103     Anil     Mumbai         2000
3       104      Ram  Hyderabad         1200

<h3 style="color:blue;text-align:center">Categorical Methods</h3>

In [97]:
df = pd.DataFrame({
    'customer': ['Ram', 'Shyam', 'Anil', 'Ram', 'Anil'],
    'city': ['Hyderabad', 'Delhi', 'Mumbai', 'Hyderabad', 'Delhi'],
    'membership': ['Gold', 'Silver', 'Gold', 'Platinum', 'Silver'],
    'age': [25, 30, 35, 28, 40],
    'spending': [1000, 1500, 2000, 1200, 1800]
})

print(df)

  customer       city membership  age  spending
0      Ram  Hyderabad       Gold   25      1000
1    Shyam      Delhi     Silver   30      1500
2     Anil     Mumbai       Gold   35      2000
3      Ram  Hyderabad   Platinum   28      1200
4     Anil      Delhi     Silver   40      1800

In [98]:
df.dtypes

customer      object
city          object
membership    object
age            int64
spending       int64
dtype: object

In [99]:
# convert column -> categorical

df['membership'] = df['membership'].astype('category')

print(df)

  customer       city membership  age  spending
0      Ram  Hyderabad       Gold   25      1000
1    Shyam      Delhi     Silver   30      1500
2     Anil     Mumbai       Gold   35      2000
3      Ram  Hyderabad   Platinum   28      1200
4     Anil      Delhi     Silver   40      1800

In [100]:
# convert categories to numeric codes

df['membership'].cat.codes

0    0
1    2
2    0
3    1
4    2
dtype: int8

In [101]:
# Get Unique categories

df['membership'].cat.categories

Index(['Gold', 'Platinum', 'Silver'], dtype='object')

In [102]:
# Rename category lables

df['membership'] = df['membership'].cat.rename_categories({
  'Gold':'G',
  'Silver':'S',
  'Platinum':'P'
})

print(df)

  customer       city membership  age  spending
0      Ram  Hyderabad          G   25      1000
1    Shyam      Delhi          S   30      1500
2     Anil     Mumbai          G   35      2000
3      Ram  Hyderabad          P   28      1200
4     Anil      Delhi          S   40      1800

In [103]:
# add new category

df['membership'] = df['membership'].cat.add_categories(['Diomand'])

print(df)

  customer       city membership  age  spending
0      Ram  Hyderabad          G   25      1000
1    Shyam      Delhi          S   30      1500
2     Anil     Mumbai          G   35      2000
3      Ram  Hyderabad          P   28      1200
4     Anil      Delhi          S   40      1800

In [104]:
df['membership'].cat.categories

Index(['G', 'P', 'S', 'Diomand'], dtype='object')

In [105]:
# Remove Category

df['membership'] = df['membership'].cat.remove_categories(['S'])

print(df)

  customer       city membership  age  spending
0      Ram  Hyderabad          G   25      1000
1    Shyam      Delhi        NaN   30      1500
2     Anil     Mumbai          G   35      2000
3      Ram  Hyderabad          P   28      1200
4     Anil      Delhi        NaN   40      1800

<h3 style="color:blue;text-align:center">Boolean & Conditional</h3>

In [ ]:
# isint()
# -> check multiple values


df[df['city'].isin(['Hyderabad','Delhi','Bengaluru'])]

  customer       city membership  age  spending
0      Ram  Hyderabad          G   25      1000
1    Shyam      Delhi        NaN   30      1500
3      Ram  Hyderabad          P   28      1200
4     Anil      Delhi        NaN   40      1800

In [ ]:
# between
# Range filtering

df[df['age'].between(25,30)]

In [ ]:
# all -> if all values are true
# any -> if any one value is true