<h3 style="color:blue;text-align:center">Inspection Methods </h3>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [65]:
df = pd.read_csv("./Data/car_price_dataset.csv")

df.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [3]:
# first 5 rows
df.head()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [4]:
# last five rows
df.tail()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [5]:
# schema summary

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car_ID        2000 non-null   int64
 1   Brand         2000 non-null   object
 2   Model_Year    2000 non-null   int64
 3   Engine_Size   2000 non-null   float64
 4   Fuel_Type     2000 non-null   object
 5   Transmission  2000 non-null   object
 6   Mileage       2000 non-null   int64
 7   Doors         2000 non-null   int64
 8   Owner_Count   2000 non-null   int64
 9   Horsepower    2000 non-null   int64
 10  Price         2000 non-null   float64
dtypes: float64(2), int64(6), object(3)
memory usage: 172.0+ KB

In [6]:
# statistical summary

df.describe()

,Car_ID,Model_Year,Engine_Size,Mileage,Doors,Owner_Count,Horsepower,Price
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,1000.500000,2013.963000,2.967550,100736.956500,2.988000,2.532500,235.70950,46169.507675
std,577.494589,5.508248,1.146926,56002.915221,0.818041,1.125423,95.59811,9211.685713
min,1.000000,2005.000000,1.000000,5036.000000,2.000000,1.000000,70.00000,18911.550000
25%,500.750000,2009.000000,2.000000,52365.500000,2.000000,2.000000,154.00000,39764.000000
50%,1000.500000,2014.000000,2.900000,100590.500000,3.000000,3.000000,236.00000,46112.350000
75%,1500.250000,2019.000000,4.000000,148024.500000,4.000000,4.000000,319.00000,52471.387500
max,2000.000000,2023.000000,5.000000,199904.000000,4.000000,4.000000,399.00000,72267.800000

In [7]:
df.describe(include='all')

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
count,2000.000000,2000,2000.000000,2000.000000,2000,2000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
unique,NaN,6,NaN,NaN,4,2,NaN,NaN,NaN,NaN,NaN
top,NaN,Toyota,NaN,NaN,Diesel,Automatic,NaN,NaN,NaN,NaN,NaN
freq,NaN,352,NaN,NaN,537,1018,NaN,NaN,NaN,NaN,NaN
mean,1000.500000,NaN,2013.963000,2.967550,NaN,NaN,100736.956500,2.988000,2.532500,235.70950,46169.507675
std,577.494589,NaN,5.508248,1.146926,NaN,NaN,56002.915221,0.818041,1.125423,95.59811,9211.685713
min,1.000000,NaN,2005.000000,1.000000,NaN,NaN,5036.000000,2.000000,1.000000,70.00000,18911.550000
25%,500.750000,NaN,2009.000000,2.000000,NaN,NaN,52365.500000,2.000000,2.000000,154.00000,39764.000000
50%,1000.500000,NaN,2014.000000,2.900000,NaN,NaN,100590.500000,3.000000,3.000000,236.00000,46112.350000
75%,1500.250000,NaN,2019.000000,4.000000,NaN,NaN,148024.500000,4.000000,4.000000,319.00000,52471.387500
max,2000.000000,NaN,2023.000000,5.000000,NaN,NaN,199904.000000,4.000000,4.000000,399.00000,72267.800000

In [8]:
# memory consumed by each column

df.memory_usage(deep=True)

Index              128
Car_ID           16000
Brand           124048
Model_Year       16000
Engine_Size      16000
Fuel_Type       126968
Transmission    129054
Mileage          16000
Doors            16000
Owner_Count      16000
Horsepower       16000
Price            16000
dtype: int64

In [9]:
# shape

df.shape

(2000, 11)

In [10]:
# size

df.size

22000

In [11]:
# number of dimensions

df.ndim

2

In [12]:
# list of axes (index + columns)

df.axes

[RangeIndex(start=0, stop=2000, step=1),
 Index(['Car_ID', 'Brand', 'Model_Year', 'Engine_Size', 'Fuel_Type',
        'Transmission', 'Mileage', 'Doors', 'Owner_Count', 'Horsepower',
        'Price'],
       dtype='object')]

In [13]:
# checks if dataframe is empty

df.empty

False

In [14]:
# column names

df.columns

Index(['Car_ID', 'Brand', 'Model_Year', 'Engine_Size', 'Fuel_Type',
       'Transmission', 'Mileage', 'Doors', 'Owner_Count', 'Horsepower',
       'Price'],
      dtype='object')

In [15]:
# iterate over columns

for col_name,data in df.items():
  print(col_name)

Car_ID
Brand
Model_Year
Engine_Size
Fuel_Type
Transmission
Mileage
Doors
Owner_Count
Horsepower
Price

In [16]:
# select data types

df.select_dtypes(include=["int"])

      Car_ID  Model_Year  Mileage  Doors  Owner_Count  Horsepower
0          1        2023   180635      4            3          82
1          2        2018    35628      2            4         259
2          3        2008    74672      3            2         333
3          4        2017    51246      4            4         381
4          5        2012   147233      3            4         290
...      ...         ...      ...    ...          ...         ...
1995    1996        2023   155033      2            3         310
1996    1997        2023    25044      2            4         271
1997    1998        2022   104372      4            3         191
1998    1999        2020   158047      4            1         186
1999    2000        2012    19706      3            1         165

[2000 rows x 6 columns]

<h3 style="color:orange;text-align:center">Indexing and Slicing </h3>

```
loc[row_label,column_label]
```

In [17]:
df.loc[5]

Car_ID                  6
Brand               Honda
Model_Year           2023
Engine_Size           3.5
Fuel_Type          Petrol
Transmission    Automatic
Mileage             94110
Doors                   2
Owner_Count             4
Horsepower            173
Price             54182.5
Name: 5, dtype: object

In [18]:
df.loc[5,"Transmission"]

'Automatic'

In [19]:
df.loc[2:6]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
5,6,Honda,2023,3.5,Petrol,Automatic,94110,2,4,173,54182.50
6,7,BMW,2016,2.3,Petrol,Manual,7810,2,3,267,52140.50

In [20]:
df.loc[:,"Brand":"Engine_Size"]

        Brand  Model_Year  Engine_Size
0        Ford        2023          1.2
1     Hyundai        2018          3.2
2         BMW        2008          2.2
3     Hyundai        2017          2.2
4     Hyundai        2012          2.4
...       ...         ...          ...
1995  Hyundai        2023          4.5
1996   Toyota        2023          1.4
1997  Hyundai        2022          4.1
1998      BMW        2020          4.4
1999    Honda        2012          1.7

[2000 rows x 3 columns]

In [21]:
df.loc[:,["Brand","Model_Year"]]

        Brand  Model_Year
0        Ford        2023
1     Hyundai        2018
2         BMW        2008
3     Hyundai        2017
4     Hyundai        2012
...       ...         ...
1995  Hyundai        2023
1996   Toyota        2023
1997  Hyundai        2022
1998      BMW        2020
1999    Honda        2012

[2000 rows x 2 columns]

In [22]:
# boolean filtering

df.loc[df['Model_Year']>2022]

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
5,6,Honda,2023,3.5,Petrol,Automatic,94110,2,4,173,54182.50
10,11,Ford,2023,4.1,Petrol,Automatic,198435,2,3,318,56053.25
15,16,Ford,2023,1.2,Hybrid,Automatic,75864,2,3,226,46896.80
27,28,Toyota,2023,2.7,Electric,Manual,15435,2,4,216,55129.25
...,...,...,...,...,...,...,...,...,...,...,...
1970,1971,Honda,2023,1.2,Diesel,Automatic,158048,4,4,287,44734.60
1979,1980,Ford,2023,3.9,Petrol,Manual,177614,3,4,144,49746.30
1987,1988,Ford,2023,1.5,Electric,Manual,39033,4,3,261,52847.35
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80

```
iloc[row_index,column_index]
```

In [23]:
df.iloc[0]

Car_ID                 1
Brand               Ford
Model_Year          2023
Engine_Size          1.2
Fuel_Type         Hybrid
Transmission      Manual
Mileage           180635
Doors                  4
Owner_Count            3
Horsepower            82
Price           34309.25
Name: 0, dtype: object

In [24]:
df.iloc[0,1]

'Ford'

```
at[row_label,column_label]
```

1. Accessing only single values

In [25]:
df.at[5,"Mileage"]

np.int64(94110)

```
iat[row_index,column_index]
```

In [26]:
df.iat[0,1]

'Ford'

```
take -> Fast Positional selection
```

In [27]:
df.take([0,2,4])

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35

In [28]:
df.take([0,2,4],axis=1)

      Car_ID  Model_Year Fuel_Type
0          1        2023    Hybrid
1          2        2018  Electric
2          3        2008    Diesel
3          4        2017    Petrol
4          5        2012  Electric
...      ...         ...       ...
1995    1996        2023    Diesel
1996    1997        2023    Petrol
1997    1998        2022    Diesel
1998    1999        2020    Diesel
1999    2000        2012  Electric

[2000 rows x 3 columns]

<h3 style="color:blue;text-align:center">Cleaning Methods</h3>

In [29]:
# Returns True/False mask for missing values

df.isna()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False,False,False

In [30]:
# Returns True for non-missing values

df.notna()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
1995,True,True,True,True,True,True,True,True,True,True,True
1996,True,True,True,True,True,True,True,True,True,True,True
1997,True,True,True,True,True,True,True,True,True,True,True
1998,True,True,True,True,True,True,True,True,True,True,True
1999,True,True,True,True,True,True,True,True,True,True,True

In [31]:
# drop rows with any NaN

df.dropna()

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [32]:
# Remove null values in Axis wise

df.dropna(axis=1)

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [ ]:
# Replace missing values

# Methods
# 1. Forwardfill
# 2. Backwardfill


df.fillna(None,method="ffill")

In [33]:
# Replace specific value with other value

df.replace("Honda","Suzuki")

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Suzuki,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [34]:
# Multiple replacement values

df.replace({"Diesel":"diesel","Petrol":"petrol"})

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

```
interpolate() -> Fill missing values using mathematical interpolation
```

#### Methods

1. linear
2. time
3. polynomial

In [48]:
df = pd.DataFrame({
  "age":[1,None,4,4,3,None],
  "name":["Ram","Prasanth","Ramanji","Ramanji","Siva","Parvathi"]
})

print(df)

   age      name
0  1.0       Ram
1  NaN  Prasanth
2  4.0   Ramanji
3  4.0   Ramanji
4  3.0      Siva
5  NaN  Parvathi

In [49]:
df.interpolate() # default linear

C:\Users\prasa\AppData\Local\Temp\ipykernel_6380\581028858.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate() # default linear

   age      name
0  1.0       Ram
1  2.5  Prasanth
2  4.0   Ramanji
3  4.0   Ramanji
4  3.0      Siva
5  3.0  Parvathi

In [50]:
df.interpolate(method="polynomial",order=2)

C:\Users\prasa\AppData\Local\Temp\ipykernel_6380\2205026850.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="polynomial",order=2)

   age      name
0  1.0       Ram
1  3.0  Prasanth
2  4.0   Ramanji
3  4.0   Ramanji
4  3.0      Siva
5  NaN  Parvathi

```
drop_duplicates
```
##### Keep values
1. first
2. last
3. false

In [51]:
# remove all duplicates

df.drop_duplicates(keep="first")

   age      name
0  1.0       Ram
1  NaN  Prasanth
2  4.0   Ramanji
4  3.0      Siva
5  NaN  Parvathi

In [52]:
# Find duplicated rows

df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

```
infer_objects() -> Automatically convert object dtypes to better types
```

In [53]:
df = pd.DataFrame({
  "A":["1","2","3"]
})

df.dtypes

A    object
dtype: object

In [54]:
df = df.infer_objects()
df.dtypes

A    object
dtype: object

##### Convert_dtypes()

- convert columns to best possible dtype

In [57]:
df.dtypes

Car_ID            int64
Brand            object
Model_Year        int64
Engine_Size     float64
Fuel_Type        object
Transmission     object
Mileage           int64
Doors             int64
Owner_Count       int64
Horsepower        int64
Price           float64
dtype: object

In [59]:
df.convert_dtypes().dtypes

Car_ID                   Int64
Brand           string[python]
Model_Year               Int64
Engine_Size            Float64
Fuel_Type       string[python]
Transmission    string[python]
Mileage                  Int64
Doors                    Int64
Owner_Count              Int64
Horsepower               Int64
Price                  Float64
dtype: object

<h3 style="color:orange;text-align:center">Transformation Methods</h3>

In [61]:
# astype()
# - Convert data type of a column or entire dataframe

df = pd.DataFrame({
  "Age":['2','3','4']
})

print(df.dtypes)
df.head()

Age    object
dtype: object

  Age
0   2
1   3
2   4

In [64]:
df = df.astype(int)
df.dtypes

Age    int64
dtype: object

In [67]:
# converting data type of multiple columns

df = df.astype({"Doors":"float","Owner_Count":"float"})

df.dtypes

Car_ID            int64
Brand            object
Model_Year        int64
Engine_Size     float64
Fuel_Type        object
Transmission     object
Mileage           int64
Doors           float64
Owner_Count     float64
Horsepower        int64
Price           float64
dtype: object

In [68]:
# apply()
# - Apply a function along rows or columns


df = pd.DataFrame({
  "A":[1,2,3]
})

df['A_Squared'] = df['A'].apply(lambda x : x**2)

df.head()

   A  A_Squared
0  1          1
1  2          4
2  3          9

In [69]:
# applymap()
# - Apply function to every element of DataFrame

df = pd.DataFrame({
  "A":[1,2],
  "B":[3,4]
})

df.applymap(lambda x: x*10)

C:\Users\prasa\AppData\Local\Temp\ipykernel_6380\3968093004.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x*10)

    A   B
0  10  30
1  20  40

In [73]:
# map()
# - Transform values in a Series (Single column)

df = pd.DataFrame({
  "gender":np.random.choice(["Male","Female"],10)
})

df["gender"] = df["gender"].map({"Male":0,"Female":1})

df.head()

   gender
0       0
1       1
2       1
3       0
4       1

In [74]:
# transform()
# - Transform Data but keep same shape


df = pd.DataFrame({
  "A":[1,2,3]
})

df['A_doubled'] =df['A'].transform(lambda x: x*2)
df

   A  A_doubled
0  1          2
1  2          4
2  3          6

In [75]:
# pipe()
# - Chain Functions for clean and readable code


def add_column(df):
  df["Sum"] = df["A"] + df["A_doubled"]
  return df

df = df.pipe(add_column)

df

   A  A_doubled  Sum
0  1          2    3
1  2          4    6
2  3          6    9

<h3 style="color:orange;text-align:center">Sorting Methods</h3>

```
sort_values()

1. by -> column names
2. axis -> axes
3. ascending
4. inplace
5. na_position -> First/Last
```

In [8]:
df = pd.DataFrame({
  "Age":np.random.randint(10,60,20),
  "gender":np.random.choice(["Male","Female","Other"],20),
  "department":np.random.choice(["HR","Developer","Team Lead","UI/UX"],20)
})

In [9]:
# sort values
df.sort_values(by="Age",axis=0,ascending=True,na_position="first")

    Age  gender department
7    12  Female  Developer
18   14  Female         HR
6    15  Female  Team Lead
2    16   Other  Developer
11   17  Female  Team Lead
19   21    Male      UI/UX
0    24    Male         HR
5    25    Male         HR
8    32  Female  Team Lead
14   34    Male  Team Lead
4    37   Other  Developer
17   39  Female  Team Lead
1    41    Male  Developer
13   46    Male      UI/UX
10   51  Female      UI/UX
12   53  Female         HR
3    58   Other  Developer
9    58    Male      UI/UX
15   59   Other  Developer
16   59  Female      UI/UX

In [11]:
df

    Age  gender department
0    24    Male         HR
1    41    Male  Developer
2    16   Other  Developer
3    58   Other  Developer
4    37   Other  Developer
5    25    Male         HR
6    15  Female  Team Lead
7    12  Female  Developer
8    32  Female  Team Lead
9    58    Male      UI/UX
10   51  Female      UI/UX
11   17  Female  Team Lead
12   53  Female         HR
13   46    Male      UI/UX
14   34    Male  Team Lead
15   59   Other  Developer
16   59  Female      UI/UX
17   39  Female  Team Lead
18   14  Female         HR
19   21    Male      UI/UX

In [13]:
df

    Age  gender department
0    24    Male         HR
1    41    Male  Developer
2    16   Other  Developer
3    58   Other  Developer
4    37   Other  Developer
5    25    Male         HR
6    15  Female  Team Lead
7    12  Female  Developer
8    32  Female  Team Lead
9    58    Male      UI/UX
10   51  Female      UI/UX
11   17  Female  Team Lead
12   53  Female         HR
13   46    Male      UI/UX
14   34    Male  Team Lead
15   59   Other  Developer
16   59  Female      UI/UX
17   39  Female  Team Lead
18   14  Female         HR
19   21    Male      UI/UX

In [14]:
dff = pd.DataFrame({
  "Name":["Ram","Prasanth","Bala Murali","Lakshmi","Malleswari"],
  "Gender":np.random.choice(["Male","Female","Other"],5),
  "Department":np.random.choice(["HR","Finance","Tech","Developer"],5),
  "Age":np.random.randint(23,35,5)
})

print(dff.head())

          Name  Gender Department  Age
0          Ram   Other  Developer   29
1     Prasanth  Female         HR   32
2  Bala Murali  Female  Developer   28
3      Lakshmi    Male  Developer   27
4   Malleswari    Male         HR   29

In [15]:
# setting indexes

dff.index = ['a','b','c','d','e']

print(dff.head())

          Name  Gender Department  Age
a          Ram   Other  Developer   29
b     Prasanth  Female         HR   32
c  Bala Murali  Female  Developer   28
d      Lakshmi    Male  Developer   27
e   Malleswari    Male         HR   29

In [16]:
# setting column name as a index

dff = dff.set_index("Name")

print(dff.head())

             Gender Department  Age
Name
Ram           Other  Developer   29
Prasanth     Female         HR   32
Bala Murali  Female  Developer   28
Lakshmi        Male  Developer   27
Malleswari     Male         HR   29

In [17]:
# sort_index()
# - It is used to sort DataFrame or series based on index (row labels,or column labels)

dff = dff.sort_index(ascending=True)

print(dff)

             Gender Department  Age
Name
Bala Murali  Female  Developer   28
Lakshmi        Male  Developer   27
Malleswari     Male         HR   29
Prasanth     Female         HR   32
Ram           Other  Developer   29

In [18]:
# sort columns instead of rows

dff.sort_index(axis=1,inplace=True)

print(dff)

             Age Department  Gender
Name
Bala Murali   28  Developer  Female
Lakshmi       27  Developer    Male
Malleswari    29         HR    Male
Prasanth      32         HR  Female
Ram           29  Developer   Other

In [19]:
# resetting index means back to normal

dff = dff.reset_index()

print(dff.head())

          Name  Age Department  Gender
0  Bala Murali   28  Developer  Female
1      Lakshmi   27  Developer    Male
2   Malleswari   29         HR    Male
3     Prasanth   32         HR  Female
4          Ram   29  Developer   Other

```
nlargest()
```

1. Get top N largest values

In [27]:
print(dff.nlargest(2,["Age"]))

         Name  Age Department  Gender
3    Prasanth   32         HR  Female
2  Malleswari   29         HR    Male

```
nsmallest()
```
1. Get top N Smallest Value

In [28]:
print(dff.nsmallest(3,"Age"))

          Name  Age Department  Gender
1      Lakshmi   27  Developer    Male
0  Bala Murali   28  Developer  Female
2   Malleswari   29         HR    Male

<h3 style="color:orange;text-align:center">Merging and Joining</h3>

```
merge()
```

* Methods
1. inner -> common values only
2. left -> all from left
3. right -> all from right
4. outer -> all from both

In [11]:
orders = pd.DataFrame({
  "order_id":[101,102,103,104],
  "customer_id":[1,2,2,5],
  "amount":[500,700,300,900]
})

print(orders)

   order_id  customer_id  amount
0       101            1     500
1       102            2     700
2       103            2     300
3       104            5     900

In [4]:
orders = orders.set_index("customer_id")
print(orders)

             order_id  amount
customer_id
1                 101     500
2                 102     700
2                 103     300
5                 104     900

In [12]:
customers = pd.DataFrame({
  "customer_id":[1,2,3,4],
  "name":["Ram","Shyam","Ravi","Anu"],
  "city":["Hyderabad","Delhi","Mumbai","Chennai"]
})

print(customers)

   customer_id   name       city
0            1    Ram  Hyderabad
1            2  Shyam      Delhi
2            3   Ravi     Mumbai
3            4    Anu    Chennai

In [33]:
payments = pd.DataFrame({
  "order_id":[101,102,103],
  "status":["Paid","Pending","Paid"]
})

print(payments)

   order_id   status
0       101     Paid
1       102  Pending
2       103     Paid

In [36]:
backup_customers = pd.DataFrame({
  "customer_id":[1,2,3,4],
  "name":["Ram",None,"Ravi","Anu"],
  "city":["Hyderabad","Delhi",None,"Chennai"]
})

print(backup_customers)

   customer_id  name       city
0            1   Ram  Hyderabad
1            2  None      Delhi
2            3  Ravi       None
3            4   Anu    Chennai

In [37]:
# combine customers + orders

pd.merge(customers,orders,on="customer_id",how="inner")

   customer_id   name       city  order_id  amount
0            1    Ram  Hyderabad       101     500
1            2  Shyam      Delhi       102     700
2            2  Shyam      Delhi       103     300

```
join()
```
- Join Dataframe using Index

In [ ]:
customers.reset_index()
customers.columns

Index(['customer_id', 'name', 'city'], dtype='object')

In [10]:
orders.reset_index()
orders.columns

Index(['order_id', 'amount'], dtype='object')

```
concat()
```
1. Combine DataFrames along rows or columns

             order_id  amount
customer_id
1                 101     500
2                 102     700
2                 103     300
5                 104     900

In [16]:
pd.concat([customers,orders],axis=1)

   customer_id   name       city  order_id  customer_id  amount
0            1    Ram  Hyderabad       101            1     500
1            2  Shyam      Delhi       102            2     700
2            3   Ravi     Mumbai       103            2     300
3            4    Anu    Chennai       104            5     900